"""update_chunk_id_to_string_and_add_metadata

Revision ID: a3f162f52c95
Revises: 8cedc585996f
Create Date: 2026-05-01 03:56:01.795145

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import VECTOR
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f162f52c95'
down_revision: Union[str, Sequence[str], None] = '8cedc585996f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.alter_column('document_chunks', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('document_chunks', 'embedding',
               existing_type=VECTOR(dim=1536),
               type_=VECTOR(dim=3072),
               existing_nullable=True)
    op.add_column('documents', sa.Column('file_hash', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'documents', ['file_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_column('documents', 'file_hash')
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    op.alter_column('document_chunks', 'id',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('document_chunks', 'metadata_json')
    # ### end Alembic commands ###
